// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "Characters/ExoCharacterBase.h"
#include "ExoPlayerCharacter.generated.h"

class UInteractionComponent;
class UShootingComponent;

UCLASS()
class EXO_API AExoPlayerCharacter : public AExoCharacterBase
{
	GENERATED_BODY()

public:
	AExoPlayerCharacter();

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	TObjectPtr<UInteractionComponent> InteractionComponent;
	
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly)
	TObjectPtr<UShootingComponent> ShootingComponent;

	UPROPERTY(EditAnywhere, Category = "Dodge Properties")
	float DodgeForce = 5000.f;

	UPROPERTY(EditAnywhere, Category = "Dodge Properties")
	float DodgeCooldown = 2.f;

	UPROPERTY(EditAnywhere, Category = "Movement Properties")
	float WalkSpeed = 600.0f;

	UPROPERTY(EditAnywhere, Category = "Movement Properties")
	float SprintSpeed = 1500.0f;

protected:
	virtual void BeginPlay() override;

	
};
